!include C4-PlantUML/C4_Container.puml
!include Azure-PlantUML/AzureCommon.puml
!include Azure-PlantUML/AzureC4Integration.puml
!include Azure-PlantUML/AIMachineLearning/all.puml
!include Azure-PlantUML/Analytics/all.puml
!include Azure-PlantUML/Compute/all.puml
!include Azure-PlantUML/Containers/all.puml
!include Azure-PlantUML/Databases/all.puml
!include Azure-PlantUML/DevOps/all.puml
!include Azure-PlantUML/General/all.puml
!include Azure-PlantUML/Identity/all.puml
!include Azure-PlantUML/Integration/all.puml
!include Azure-PlantUML/InternetOfThings/all.puml
!include Azure-PlantUML/Management/all.puml
!include Azure-PlantUML/Media/all.puml
!include Azure-PlantUML/Mobile/all.puml
!include Azure-PlantUML/Networking/all.puml
!include Azure-PlantUML/Security/all.puml
!include Azure-PlantUML/Storage/all.puml
!include Azure-PlantUML/Web/all.puml